### ISSUE TITLE
Add a composer.json and publish on packagist 

### ISSUE THREAD

**Issue by basz** [NoahjChampion/kingcomposer#2]
Since you now have a public git repo... :-) a first feature request specifically for developers.

references:
https://wpackagist.org
https://pantheon.io/blog/web-docroot-wordpress-composer

example composer.json
```
{
  "repositories": [
    {
      "type": "composer",
      "url": "https://wpackagist.org"
    }
  ],
  "require": {
    "php": ">=5.4",
    "johnpbloch/wordpress": "^4.8",
    "wpackagist-plugin/kingcomposer": "^2.6"
  },
  "extra": {
    "wordpress-install-dir": "wordpress"
  }
}
```

cheers, great plugin!

**Comment by NoahjChampion** [comment]
@basz Thanks for requesting anything 👍 

About this, would you provide a real world example of how this benefits the developer?

Over the next month or so we are working on specifically the developer license. Not that I think this feature would be exclusive to that but could be worked in the loop of the developer focused work load.

I'm not familiar with this so if you could break it down to me in simple clear way, that would help!!!

**Comment by basz** [comment]
I'm not sure what your level of familiarity with composer is, so...

Composer is package manager for PHP packages. Similar like NPM or bower is for javascript.

It helps with managing dependencies you might use in a project. It can help with automated builds or deployments. It can help in production vs development requirements. For example, [unittesting](https://github.com/sebastianbergmann/phpunit) is only needed while developing. On a Continues Integration server you would install with dev dependencies, but in production you wouldn't.Additionally composer solves autoloading, which is useful in any project.

Composer is the [defacto](https://github.com/search?l=JSON&q=composer+extension%3Ajson+path%3A%2F&ref=advsearch&type=Code&utf8=✓) package manager for PHP. Anyone who publishes a composer.json with there project is installable from the command line by calling `composer require my/packge`. Immediately developers are able to use any classes it provides.

Now, I am aware wordpress has it's own methodologies and as such is special case and many devs aren't from a dev background. Yet I predict wordpress will slowly move toward using composer too. As you can see on wpackagist.org there are already many on the composer bandwagon.

I personally used it because I needed to create a image processing plugin that needed a library (the actual images processing). With one command I can install the plugin and all of it dependencies without placing those dependencies in source control.

**Comment by basz** [comment]
To add to this; it means that when a wordpress plugin provides a composer.json file, registers it as a package at packagist and declare a special tag in the composer.json composer can install it with `composer require wpackagist-plugin/kingcomposer` into the wp-plugin dir. The same thing is possible for themes and wordpress itself. Developer oriented users may also choose to use `composer update` to retrieve a more recent versions of any install package/plugin/theme. You are able to decouple the plugin source from other libraries your plugin or theme may require. The wordpress GUI would still works of course. However I can think of at least one issue; if your plugin needs to do database migrations this might not work, because `composer update` doesn't run in the wordpress application which currently does db migrations if needed. But I'm not sure how wordpress handles that at the moment. If you have any questions please don't hesitate to ask...

**Comment by basz** [comment]
hmm, seems it is already possible without jumping through hoops.

https://www.dropbox.com/s/ifs6zbq14bsbeia/composer.mov?dl=0 

I guess it is mostly advantage when a plugin or theme has dependencies of its own.

**Comment by NoahjChampion** [comment]
Hi, @basz would you send me an email noahj [at] fearlessmode [dot] com?
