### ISSUE TITLE
incorrect z-index values in Text Block MCE editor

### ISSUE THREAD

**Issue by achilles283** [NoahjChampion/kingcomposer#3]
On a clean WP install, the text format (paragraph, H1, H2, etc) dropdown and text color picker tooltip/options display behind the modal in the Text Block Settings - General Tab.

![screenshot 2017-09-12 09 46 15](https://user-images.githubusercontent.com/115354/30332222-6a42bb40-979f-11e7-9ab1-6cc9f955df05.png)
![screenshot 2017-09-12 09 46 42](https://user-images.githubusercontent.com/115354/30332221-6a42bb9a-979f-11e7-8213-4a4605d4d60e.png)
![screenshot 2017-09-12 09 47 13](https://user-images.githubusercontent.com/115354/30332223-6a43f0f0-979f-11e7-94b0-1c97da30a203.png)

**Comment by NoahjChampion** [comment]
@achilles283 

Thanks about this. This should be fixed in the BETA. I will either upload the BETA here or in another repo and let you know when I do so.

**Comment by achilles283** [comment]
It would be super helpful if open issues were left open until they are actually fixed and available for download. This will help others who are searching for the same problem and find that it is a known issue and slated to be resolved.

If the fix is already known, it would also be great if it was added to this repo so others (and myself) can deploy to client websites if the fix is minor. The fix could be added via a development or beta branch within this repo (develop or development is typically the standard naming convention).

Lastly, it would be great to begin leveraging git tags for release versions in this repo.

While I use the WP plugin repository, getting bug fixes is typically very slow and by leveraging GitHub, I can safely implement bug fixes without worrying about updating the plugin via the admin in the future because of the transparency this workflow affords. For example, I will know the patch I have implemented manually for clients will be rolled out with the update via the plugin admin since I can see it has been merged here.

Thanks!

**Comment by NoahjChampion** [comment]
@achilles283 

Ok, understood, sounds good. REOPENED 💯 

I'm actually official help with KC and the Git is needed for tracking/organization, public visibility, feedback, etc. as well as so I can push my edits too. We also (and by we, I mean ALL, you, I, others) can greatly benefit from developers input and contributions in this format. Though the core KC devs use Bitbucket and the repo is full at the moment. 

I will need a little time to just think about how I want organize this repo and or BETA with the workflow we have already. We have about 50 items already that I could place in this Repo I'm thinking, check off what is done, so all devs, etc. can see and also help with any at all as well if they desire or come across and fix it themselves.

**Comment by achilles283** [comment]
@NoahjChampion Thanks man, that sounds super helpful/awesome! I love the work you all have done and will help out in any way I can.

**Comment by NoahjChampion** [comment]
@achilles283 

Awesome!!! Good to hear and appreciate you and your pull man. #Salute

**Comment by NoahjChampion** [comment]
Hi, @achilles283 would you send me an email noahj [at] fearlessmode [dot] com?
