### ISSUE TITLE
Content edits are saved/published on preview

### ISSUE THREAD

**Issue by achilles283** [NoahjChampion/kingcomposer#4]
After editing a page via KC, if the user selects "Preview Changes", the edits are saved and published.

**Comment by NoahjChampion** [comment]
@achilles283 

Hi, yes we are aware and there is a fix already written by another user who I thought would be first to create a pull request, but I haven't heard back from him yet. I will follow up on that.

**Comment by achilles283** [comment]
@NoahjChampion I believe that person is me ;) - I was just creating a ticket so it is tracked before submitting my fix/pull request since it is an open issue and for others that may be looking for a solution.

Should have my solution to you in a few.

**Comment by NoahjChampion** [comment]
@achilles283 Ok! I did actually think it was you but since you mentioned it without the repo I deferred to it not being you, haha. 

Ok, great. Thanks!
